### PR TITLE
fix: position encoding to ensure correct formatting for special chars

### LINKED ISSUE #242: Formatting add space inside strings, when using special char.
This happens with new expert nightly build, eglot and emacs.

Having this:
```
[
  {"Karolína Plíšková","Kristýna Plíšková"}
  
]
```

and running 'eglot-format-buffer' using experts formats as:
```

[
  {"Karolína Plíšková","Kri stýna Plíšková"}
]
```

Note the added space. 

Running it without 'special chars' like:
```

[
  {"Karolina Pliskova", "Kristyna Pliskova"}
  
]
```
gives the expected result:

```
[
  {"Karolina Pliskova", "Kristyna Pliskova"}
]

```

### PR DESCRIPTION
**Pull request by wingyplus**
I'm working on a quick prototype to fix #242. It seems that `advance` needs to be converted to UTF-16 as per the position encoding LSP spec. The code needs to fix the code_mod_case.ex in the `apply_edits` function to convert it back to UTF-8 as well.

### CODE REVIEW

File: apps/engine/test/engine/code_mod/format_test.exs [hunk 1]
```diff
@@ -114,5 +114,23 @@ defmodule Engine.CodeMod.FormatTest do
 
       assert result == formatted()
     end
+
+    test "iss 242", %{project: project} do
```
Comment (mhanberg) [inline apps/engine/test/engine/code_mod/format_test.exs]: change this to be a real test name please

Comment (wingyplus) [reply apps/engine/test/engine/code_mod/format_test.exs]: Fixed. 🙏
