### PR TITLE
fix: fetch `hex` and `rebar` in all places

### LINKED ISSUE #484: Mix is running interactively
Mix is running interactively and prints to stdout, which leads to a permanent communication failure. I looked through calls, but there are already `--force --if-missing` flags. I guess it is coming from a different command calling `mix local.hex` under the hood

```
2026-03-02 14:22:42.640 [info] [Error - 2:22:42 PM] Client Expert: connection to server is erroring.
Header must provide a Content-Length property.
{"mix requires the hex package manager to fetch dependencies\nshall i install hex? (if running non-interactively, use \"mix local.hex --force\") [yn] content-length":"172"}
Shutting down server.
```

### PR DESCRIPTION
**Pull request by Draggu**
Close #484

I'm not sure which call it came from, but simply fetching `hex` and `rebar`, as was done before, with a few calls already in all the necessary places, should do the trick.

### CODE REVIEW

File: apps/engine/lib/engine/build/project.ex [hunk 1]
```diff
@@ -53,6 +53,8 @@ defmodule Engine.Build.Project do
       Mix.Task.clear()
       Progress.report(token, message: "Compiling #{Project.display_name(project)}")
       result = compile_in_isolation()
+      Mix.Task.run("local.hex", ~w(--force --if-missing))
+      Mix.Task.run("local.rebar", ~w(--force --if-missing))
```
Comment (mkaput) [inline apps/engine/lib/engine/build/project.ex]: worth extracting into named function isn't it?

**Comment by doorgan** [comment]
It'd be nice to know where exactly this problem happens but iirc you mentioned this issue is not reproducible reliably.
Should we check if the user may not be connected to internet before this? Otherwise it looks like Expert wouldn't work offline(not that we have *great* support for offline but still)

File: apps/engine/lib/engine/build/project.ex (hunk 1 above)
Comment (Draggu) [reply apps/engine/lib/engine/build/project.ex]: done

**Comment by doorgan** [comment]
There was an issue in CI that should be fixed on main, please rebase this branch
