### PR TITLE
fix: don't infinitely loop prompting to fetch dependencies if it fails

### LINKED ISSUE #534: endless loop of asking to fetch deps
I have a bunch of projects in a monorepo.  Expert is forever hassling me to install the deps in the first one.  I say yes, it does some stuff then asks me again.  Rinse and repeat.

Image

Logs for two presses of Yes:

```2026-03-30 13:32:33.393 [info] [Info  - 1:32:33 PM] [bubba] Running mix deps.get for bubba
2026-03-30 13:32:33.413 [info] [Info  - 1:32:33 PM] [bubba] mix deps.get completed successfully
2026-03-30 13:32:33.423 [info] [Info  - 1:32:33 PM] Stopping project node for bubba
2026-03-30 13:32:33.424 [info] [Info  - 1:32:33 PM] [bubba] Restarting engine for bubba
2026-03-30 13:32:33.445 [info] [Info  - 1:32:33 PM] [bubba] Using path: C:\Users\simon\AppData\Local\.burrito\expert_erts-15.2.7_0.1.0-rc.6-1bbd0df\erts-15.2.7\bin;C:\Users\simon\AppData\Local\Programs\Microsoft VS Code;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Tailscale\;C:\Program Files\dotnet\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\PowerShell\7\;C:\Users\simon\scoop\apps\rustup\current\.cargo\bin;C:\Users\simon\scoop\apps\postgresql\current\bin;C:\Users\simon\scoop\apps\git\current\cmd;C:\Users\simon\scoop\apps\nodejs-lts\current\bin;C:\Users\simon\scoop\apps\nodejs-lts\current;C:\Users\simon\scoop\apps\openssl\current\bin;C:\Users\simon\scoop\apps\elixir\current\bin;C:\Users\simon\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\simon\AppData\Local\Programs\Python\Python39\;C:\Users\simon\scoop\shims;C:\Users\simon\AppData\Local\Microsoft\WindowsApps;C:\Users\simon\.dotnet\tools;C:\Users\simon\AppData\Local\Programs\Zed\bin;C:\Users\simon\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\simon\AppData\Local\JetBrains\Toolbox\scripts;C:\Users\simon\AppData\Local\Expert\;C:\Users\simon\AppData\Local\Programs\Swift\Runtimes\6.2.1\usr\bin\;C:\Users\simon\AppData\Local\Programs\Swift\Toolchains\6.2.1+Asserts\usr\bin\;C:\Users\simon\AppData\Local\Microsoft\WinGet\Links;C:\Users\simon\AppData\Local\Programs\Inno Setup 6;C:\Users\simon\AppData\Local\PowerToys\DSCModules\
2026-03-30 13:32:33.445 [info] [Info  - 1:32:33 PM] [bubba] Found elixir executable at c:/Users/simon/scoop/apps/elixir/current/bin/elixir.bat
2026-03-30 13:32:33.445 [info] [Info  - 1:32:33 PM] [bubba] Found erl executable at c:/Users/simon/scoop/shims/erl.exe
2026-03-30 13:32:33.445 [info] [Info  - 1:32:33 PM] [bubba] Preparing engine
2026-03-30 13:33:10.225 [info] [Info  - 1:33:10 PM] [bubba] Engine available at: c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns
2026-03-30 13:33:10.322 [info] [Info  - 1:33:10 PM] [bubba] ebin paths:
["c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/patch/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_briefly/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_bunt/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_credo/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_deps_nix/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_elixir_sense/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_engine/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_file_system/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_forge/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_gen_lsp/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_hpax/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_jason/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_mint/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_nimble_options/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_nimble_parsec/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_path_glob/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_quokka/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_refactorex/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_schematic/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_sourceror/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_spitfire/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_telemetry/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_typed_struct/ebin"]
2026-03-30 13:33:14.115 [info] [Info  - 1:33:14 PM] Started project node for bubba
2026-03-30 13:33:14.115 [info] [Info  - 1:33:14 PM] [bubba] Engine initialized for project bubba
2026-03-30 13:33:14.447 [info] [Info  - 1:33:14 PM] Compiled bubba in 267 ms
2026-03-30 13:45:21.361 [info] [Info  - 1:45:21 PM] [bubba] Running mix deps.get for bubba
2026-03-30 13:45:21.367 [info] [Info  - 1:45:21 PM] [bubba] mix deps.get completed successfully
2026-03-30 13:45:21.372 [info] [Info  - 1:45:21 PM] Stopping project node for bubba
2026-03-30 13:45:21.373 [info] [Info  - 1:45:21 PM] [bubba] Restarting engine for bubba
2026-03-30 13:45:21.392 [info] [Info  - 1:45:21 PM] [bubba] Using path: C:\Users\simon\AppData\Local\.burrito\expert_erts-15.2.7_0.1.0-rc.6-1bbd0df\erts-15.2.7\bin;C:\Users\simon\AppData\Local\Programs\Microsoft VS Code;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Tailscale\;C:\Program Files\dotnet\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\PowerShell\7\;C:\Users\simon\scoop\apps\rustup\current\.cargo\bin;C:\Users\simon\scoop\apps\postgresql\current\bin;C:\Users\simon\scoop\apps\git\current\cmd;C:\Users\simon\scoop\apps\nodejs-lts\current\bin;C:\Users\simon\scoop\apps\nodejs-lts\current;C:\Users\simon\scoop\apps\openssl\current\bin;C:\Users\simon\scoop\apps\elixir\current\bin;C:\Users\simon\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\simon\AppData\Local\Programs\Python\Python39\;C:\Users\simon\scoop\shims;C:\Users\simon\AppData\Local\Microsoft\WindowsApps;C:\Users\simon\.dotnet\tools;C:\Users\simon\AppData\Local\Programs\Zed\bin;C:\Users\simon\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\simon\AppData\Local\JetBrains\Toolbox\scripts;C:\Users\simon\AppData\Local\Expert\;C:\Users\simon\AppData\Local\Programs\Swift\Runtimes\6.2.1\usr\bin\;C:\Users\simon\AppData\Local\Programs\Swift\Toolchains\6.2.1+Asserts\usr\bin\;C:\Users\simon\AppData\Local\Microsoft\WinGet\Links;C:\Users\simon\AppData\Local\Programs\Inno Setup 6;C:\Users\simon\AppData\Local\PowerToys\DSCModules\
2026-03-30 13:45:21.392 [info] [Info  - 1:45:21 PM] [bubba] Found elixir executable at c:/Users/simon/scoop/apps/elixir/current/bin/elixir.bat
2026-03-30 13:45:21.392 [info] [Info  - 1:45:21 PM] [bubba] Found erl executable at c:/Users/simon/scoop/shims/erl.exe
2026-03-30 13:45:21.392 [info] [Info  - 1:45:21 PM] [bubba] Preparing engine
2026-03-30 13:45:24.957 [info] [Info  - 1:45:24 PM] [bubba] Engine available at: c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns
2026-03-30 13:45:25.031 [info] [Info  - 1:45:25 PM] [bubba] ebin paths:
["c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/patch/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_briefly/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_bunt/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_credo/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_deps_nix/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_elixir_sense/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_engine/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_file_system/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_forge/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_gen_lsp/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_hpax/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_jason/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_mint/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_nimble_options/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_nimble_parsec/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_path_glob/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_quokka/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_refactorex/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_schematic/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_sourceror/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_spitfire/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_telemetry/ebin",
 "c:/Users/simon/AppData/Local/expert/Cache/0.1.0-rc.6-1bbd0df/ex-1.19.5-erl-16.3/pJ-1jFNd-FZtyPl_GEwkkA/_build/dev_ns/lib/xp_typed_struct/ebin"]
2026-03-30 13:45:28.594 [info] [Info  - 1:45:28 PM] Started project node for bubba
2026-03-30 13:45:28.594 [info] [Info  - 1:45:28 PM] [bubba] Engine initialized for project bubba
2026-03-30 13:45:28.854 [info] [Info  - 1:45:28 PM] Compiled bubba in 197 ms
```

Everything is latest version: elixir, erlang, vscode, windows.

### PR DESCRIPTION
**Pull request by doorgan**
Fix #534 

I couldn't reproduce it, but from the looks of it, it's very likely it happens because the `:clean_and_fetch_deps` handler unconditionally returns `:ok`, so the upstream code doesn't know how to properly handle a failure to fetch deps and keeps asking to fetch them again.

Also to avoid spamming further and to also provide a way for the user to properly retry deps fetching in case of error(or refuse to keep trying), a new notification and handler for a "Retry" path is added

### CODE REVIEW

File: apps/engine/lib/engine/build/state.ex [hunk 1]
```diff
@@ -88,11 +88,15 @@ defmodule Engine.Build.State do
         Logger.warning("Failed to remove build path #{path}: #{inspect(reason)}")
     end
 
-    Engine.Build.Project.fetch_deps(project)
+    result = Engine.Build.Project.fetch_deps(project)
 
-    state
+    {state, normalize_fetch_deps_result(result)}
```
Comment (katafrakt) [inline apps/engine/lib/engine/build/state.ex]: Just a loose idea, but if it's State that's calling deps fetch, maybe the result should be part of it with something like `last_deps_fetch_result`?

File: apps/engine/lib/engine/build/state.ex [hunk 2]
```diff
@@ -88,11 +88,15 @@ defmodule Engine.Build.State do
...
   end
 
+  defp normalize_fetch_deps_result({:ok, :ok}), do: :ok
+  defp normalize_fetch_deps_result({:ok, result}), do: {:ok, result}
+  defp normalize_fetch_deps_result(result), do: result
```
Comment (katafrakt) [inline apps/engine/lib/engine/build/state.ex]: The first line here would already be covered by the second one.

Comment (doorgan) [reply apps/engine/lib/engine/build/state.ex]: I have a botched rebase that I didn't finish on the weekend, I'll ping you when it's done!

**Review by katafrakt — APPROVED** [review]
