### PR TITLE
fix: handle missing metadata in indexer extractors

### LINKED ISSUE #379: Indexing never finishes
With the latest commit (`aa5ba2b`) the indexing never finishes (This might have been introduced earlier though). `Expert.log` shows:

```
23:01:39.963 [debug] sent notification server -> client $/progress
23:01:39.985 [debug] Node port message: 
23:01:39.963 [debug] sent notification server -> client $/progress

23:01:40.346 [debug] Node port message: 
23:01:40.338 [error] Task #PID<0.8758.0> started from #PID<0.8648.0> terminating
** (MatchError) no match of right hand side value: nil
    (xp_engine 0.1.0) lib/engine/search/indexer/extractors/function_reference.ex:186: XPEngine.Search.Indexer.Extractors.FunctionReference.get_reference_range/4
    (xp_engine 0.1.0) lib/engine/search/indexer/extractors/function_reference.ex:159: XPEngine.Search.Indexer.Extractors.FunctionReference.entry/6
    (xp_engine 0.1.0) lib/engine/search/indexer/extractors/function_reference.ex:137: XPEngine.Search.Indexer.Extractors.FunctionReference.extract/2
    (xp_engine 0.1.0) lib/engine/search/indexer/source/reducer.ex:97: anonymous fn/2 in XPEngine.Search.Indexer.Source.Reducer.apply_extractors/2
    (elixir 1.18.3) lib/enum.ex:2546: Enum."-reduce/3-lists^foldl/2-0-"/3
    (xp_engine 0.1.0) lib/engine/search/indexer/quoted.ex:27: anonymous fn/2 in XPEngine.Search.Indexer.Quoted.extract_entries/2
    (elixir 1.18.3) lib/macro.ex:645: anonymous fn/4 in Macro.do_traverse_args/4
    (stdlib 6.2.2) lists.erl:2343: :lists.mapfoldl_1/3
Function: &:erlang.apply/2
    Args: [#Function<4.80137936/1 in XPEngine.Search.Indexer.do_process_chunks/5>, [*** REMOVED ***]
```

### PR DESCRIPTION
**Pull request by doorgan**
Fixes #379 

The indexer was crashing because it encountered nodes with missing location metadata. I'm not sure what code exactly triggered that, I suspect it might be broken code so I added tests for that.

I also looked at other places in the indexer where we would crash on missing metadata and added error handling there too.

### CODE REVIEW

File: apps/engine/lib/engine/search/indexer/extractors/function_reference.ex [hunk 1]
```diff
@@ -156,64 +158,81 @@ defmodule Engine.Search.Indexer.Extractors.FunctionReference do
...
+               {:function, :usage},
+               range,
+               Application.get_application(module)
+             )}
+
+          _ ->
+            human_location = Reducer.human_location(reducer)
+
+            Logger.warning(
+              "Could not expand #{inspect(module)} into an alias. Please report this. (at #{human_location})"
```
Comment (mhanberg) [inline apps/engine/lib/engine/search/indexer/extractors/function_reference.ex]:
```suggestion
              "Could not expand #{inspect(module)} into an alias (at #{human_location}). Please open an issue!"
```
